sections:
  main:
    display: Main
    fields:
      basics:
        type: partial
        display: 'Entry basics'
        fieldset: _basics
      subhead:
        type: text
        display: Subhead
      lead:
        type: textarea
        display: Lead
      bg_image:
        container: main
        folder: bg
        restrict: false
        max_files: 1
        mode: grid
        type: assets
        display: 'Theme Background Image'
        width: 33
      icon:
        container: main
        folder: icons
        restrict: false
        max_files: 1
        type: assets
        display: Icon
        width: 33
      color_accent:
        fieldset: _color-accents
        type: partial
        display: 'Color Accent'
        width: 33
      template:
        type: template
        display: Template
        default: product/page
  content_blocks_section:
    display: 'Content Blocks'
    fields:
      content_blocks:
        fieldset: _blocks
        type: partial
        display: 'Content Blocks'
  footer_cta:
    display: 'Footer CTA'
    fields:
      cta:
        fieldset: _cta_form
        type: partial
        display: 'Footer CTA'
  sidebar:
    display: 'Article Metadata'
    fields:
      post_meta:
        type: partial
        display: 'Post Metadata'
        fieldset: _meta
taxonomies: false
title: 'Product Page'
