collections:
  blog: '/blog/{slug}'
  academy: '/academy/{slug}'
  events: '/events/{slug}'
  webinars: '/webinar/{slug}'
  press: '/press/{slug}'
  guides: '/guide/{slug}'
  podcasts: '/podcast/{slug}'
  people: '/about/{slug}'
taxonomies:
  tags: '/tag/{slug}'
  topics: '/discover/{slug}'
routes:
  /blog/tags: blog/taxonomies
  /search: search
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
  /things/feed:
    layout: feed
    template: feeds/things
    content_type: atom
